canvas=document.getElementById("my_canvas");
ctx=canvas.getContext("2d");
color="blue";
ctx.beginPath();
ctx.lineWidth=1;
ctx.rect(150,143,430,200);
ctx.stroke();
canvas=document.getElementById("my_canvas");
ctx=canvas.getContext("2d");
color="blue";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=5;
ctx.arc(250,200,40,0,2*Math.PI);
ctx.stroke();
canvas=document.getElementById("my_canvas");
ctx=canvas.getContext("2d");
color= "black";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=5;
ctx.arc(350,200,40,0,2*Math.PI);
ctx.stroke();
canvas=document.getElementById("my_canvas");
ctx=canvas.getContext("2d");
color= "red";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=5;
ctx.arc(450,200,40,0,2*Math.PI);
ctx.stroke();
canvas=document.getElementById("my_canvas");
ctx=canvas.getContext("2d");
color= "yellow";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=5;
ctx.arc(300,240,40,0,2*Math.PI);
ctx.stroke();
canvas=document.getElementById("my_canvas");
ctx=canvas.getContext("2d");
color= "green";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=5;
ctx.arc(400,240,40,0,2*Math.PI);
ctx.stroke();